export const mockArtworks = [
  {
    id: "1",
    title: "Sinfonía Urbana",
    artist: "Valentina Cruz",
    artistId: "1",
    discipline: "Pintura",
    price: 4500000,
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    year: 2024,
    technique: "Acrílico sobre lienzo",
    dimensions: "120 × 90 cm",
    edition: "Obra única",
    description:
      "Una exploración vibrante del caos ordenado de la ciudad moderna. Los trazos superpuestos en capas de acrílico evocan el movimiento constante de Bogotá, sus calles, sus luces y sus contradicciones. La paleta cálida contrasta con fragmentos de frialdad urbana, generando una tensión que invita a la reflexión sobre nuestra relación con el espacio que habitamos.",
    tags: ["Contemporáneo", "Urbanismo", "Expresionismo"],
    available: true,
    certificate: true,
    shipping: "Envío con seguro incluido",
  },
  {
    id: "2",
    title: "Raíces de Luz",
    artist: "Marcos Ibáñez",
    artistId: "2",
    discipline: "Escultura",
    price: 12000000,
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80",
    year: 2023,
    technique: "Bronce patinado",
    dimensions: "45 × 30 × 30 cm",
    edition: "Edición de 5 ejemplares",
    description:
      "Raíces de Luz surge de la observación de los árboles centenarios del Jardín Botánico de Medellín. La forma orgánica del bronce captura ese instante en que la luz solar filtra entre las ramas, creando una geometría efímera que la escultura convierte en permanente. Cada ejemplar de la edición tiene una pátina única, irrepetible.",
    tags: ["Naturaleza", "Bronce", "Orgánico"],
    available: true,
    certificate: true,
    shipping: "Embalaje especializado para escultura",
  },
  {
    id: "3",
    title: "Digital Dreams",
    artist: "Sofía Ramos",
    artistId: "3",
    discipline: "Arte Digital",
    price: 2800000,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    year: 2025,
    technique: "Impresión fine art + NFT",
    dimensions: "100 × 70 cm (impresión)",
    edition: "Edición de 10 + NFT único",
    description:
      "Digital Dreams nació de una residencia artística en los Andes. Las montañas nevadas procesadas a través de algoritmos generativos crean una nueva topografía que existe entre lo real y lo imaginado. La obra se entrega como impresión fine art en papel Hahnemühle y como NFT certificado en blockchain.",
    tags: ["Arte generativo", "Paisaje", "Digital"],
    available: true,
    certificate: true,
    shipping: "Impresión enviada en tubo protector",
  },
  {
    id: "4",
    title: "El Grito Quieto",
    artist: "Andrés Molina",
    artistId: "4",
    discipline: "Fotografía",
    price: 1800000,
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80",
    year: 2024,
    technique: "Fotografía analógica, impresión sobre aluminio",
    dimensions: "80 × 60 cm",
    edition: "Edición de 8 ejemplares",
    description:
      "Capturada al amanecer en el Golden Gate con cámara de medio formato, esta fotografía analógica explora la soledad monumental de las grandes estructuras humanas. El grano del celuloide aporta una textura poética que los píxeles no pueden replicar. La impresión sobre aluminio da una profundidad luminosa característica del trabajo de Molina.",
    tags: ["Análogo", "Arquitectura", "Amanecer"],
    available: true,
    certificate: true,
    shipping: "Envío con embalaje rígido",
  },
  {
    id: "5",
    title: "Cosmos Interior",
    artist: "Laura Vega",
    artistId: "1",
    discipline: "Pintura",
    price: 6200000,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    year: 2023,
    technique: "Óleo sobre madera",
    dimensions: "60 × 60 cm",
    edition: "Obra única",
    description:
      "Una ventana hacia adentro. Cosmos Interior es el resultado de tres meses de trabajo en los que Vega exploró la relación entre la meditación y la creación. Los pigmentos de óleo se superponen en más de cuarenta capas, generando una profundidad casi táctil. La madera como soporte aporta una calidez que el lienzo no ofrece.",
    tags: ["Introspección", "Óleo", "Minimalismo"],
    available: false,
    certificate: true,
    shipping: "—",
  },
  {
    id: "6",
    title: "Fragmentos",
    artist: "Diego Herrera",
    artistId: "2",
    discipline: "Instalación",
    price: 9500000,
    image: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    year: 2025,
    technique: "Instalación, vidrio, luz LED, acero",
    dimensions: "Variable (mínimo 4 × 4 m)",
    edition: "Obra única con contrato de instalación",
    description:
      "Fragmentos es una instalación que interroga la memoria colectiva. Cientos de piezas de vidrio suspendidas reflejan y dispersan la luz LED de formas distintas según el movimiento del espectador. La obra se adapta a cada espacio, generando una experiencia única en cada montaje. El precio incluye transporte, montaje y asesoría de instalación.",
    tags: ["Instalación", "Luz", "Memoria"],
    available: true,
    certificate: true,
    shipping: "Transporte y montaje incluidos",
  },
];

export const mockArtists = [
  { id: "1", name: "Valentina Cruz", discipline: "Pintura", city: "Bogotá", works: 24, image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80" },
  { id: "2", name: "Marcos Ibáñez", discipline: "Escultura", city: "Medellín", works: 18, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80" },
  { id: "3", name: "Sofía Ramos", discipline: "Arte Digital", city: "Cali", works: 41, image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80" },
  { id: "4", name: "Andrés Molina", discipline: "Fotografía", city: "Barranquilla", works: 67, image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&q=80" },
];

export const mockEvents = [
  { id: "1", title: "Noche de Galerías", date: "2026-06-14", location: "Bogotá", type: "Exposición", price: 0, image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=600&q=80", spots: 200 },
  { id: "2", title: "Taller de Arte Digital", date: "2026-06-21", location: "Medellín", type: "Taller", price: 150000, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80", spots: 30 },
  { id: "3", title: "Subasta LUX NOX", date: "2026-07-05", location: "Online", type: "Subasta", price: 0, image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80", spots: 500 },
  { id: "4", title: "Concurso de Fotografía", date: "2026-07-19", location: "Nacional", type: "Concurso", price: 0, image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80", spots: 1000 },
];

export const mockNews = [
  { id: "1", title: "LUX NOX lanza su plataforma al ecosistema artístico colombiano", excerpt: "Una nueva era para los artistas: visibilidad, comunidad y mercado en un solo lugar.", date: "2026-05-15", category: "Plataforma", image: "https://images.unsplash.com/photo-1509343256512-d77a5cb3791b?w=600&q=80" },
  { id: "2", title: "Sofía Ramos: el arte digital como lenguaje del presente", excerpt: "La artista caleña habla sobre su proceso creativo y cómo la tecnología amplifica su visión.", date: "2026-05-10", category: "Artistas", image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80" },
  { id: "3", title: "Noche de Galerías regresa en junio con 40 artistas", excerpt: "El evento más esperado del semestre abre sus puertas a coleccionistas y amantes del arte.", date: "2026-05-05", category: "Eventos", image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=600&q=80" },
];

export const mockProducts = [
  { id: "1", title: "Camiseta LUX NOX Limited", price: 85000, category: "Merch", image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80" },
  { id: "2", title: "Print Firmado — Sinfonía Urbana", price: 320000, category: "Arte", artist: "Valentina Cruz", image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80" },
  { id: "3", title: "Tote Bag Artística", price: 45000, category: "Merch", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80" },
  { id: "4", title: "Fotografía Enmarcada — El Grito Quieto", price: 480000, category: "Arte", artist: "Andrés Molina", image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&q=80" },
  { id: "5", title: "Colección NFT — Cosmos Interior", price: 750000, category: "Digital", artist: "Laura Vega", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80" },
  { id: "6", title: "Agenda Artística 2026", price: 38000, category: "Merch", image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80" },
];
